### ISSUE TITLE
Sample EIM policy in install guide

### ISSUE THREAD

**Issue by outscale-age** [outscale-dev/osc-bsu-csi-driver#12]
**Is your feature request related to a problem?/Why is this needed**
As it is not a best practice to use root AK/SK with this tool, we should provide a sample Policy document that could be attached to a less-privileged EIM user.

/feature

**Describe the solution you'd like in detail**
A sample EIM policy should be present in the README, along with the recommendation to bind this policy to an EIM user dedicated for the BSU driver.

**Describe alternatives you've considered**
Precisely listing the privileges required for managing the BSUs, but it may be over-complicated for new-comers. A sample EIM policy is a good starting point.

**Additional context**
Sample policy that could be given to users:

```json
{
    "Statement": [
        {
            "Action": [
                "api:ReadVms",
                "api:ReadVmsState",
                "api:ReadSnapshots",
                "api:CreateSnapshot",
                "api:DeleteSnapshot",
                "api:CreateVolume",
                "api:ReadVolumes",
                "api:LinkVolume",
                "api:UnlinkVolume",
                "api:UpdateVolume",
                "api:DeleteVolume"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

**Comment by aniszosc** [comment]
already present : https://github.com/outscale-dev/osc-bsu-csi-driver/blob/OSC-MIGRATION/docs/example-iam-policy.json

**Comment by outscale-age** [comment]
Ha. I missed it :) So it rather boils down to enhancing the README in that case :)

**Comment by aniszosc** [comment]
to be reolved with https://github.com/aniszosc/osc-bsu-csi-driver/commit/50dcf00859238e9d75896f6045aec066e535d241
