### ISSUE TITLE
not working in cloudgouv-eu-west-1 region

### ISSUE THREAD

**Issue by jpraysz2** [outscale-dev/osc-bsu-csi-driver#516]
/kind bug

**What happened?**
disk is not allocated
**What you expected to happen?**
disk to be allocated
**How to reproduce it (as minimally and precisely as possible)?**
try to create a disk on a cluster in cloudgouv-eu-west-1 region
**Anything else we need to know?**:
driver is given a "not Authorized" error with reference to eu-west-2 region
**Environment**
- Kubernetes version (use `kubectl version`): 1.23.14
- Driver version: 1.1.0

**Comment by jerome-jutteau** [comment]
Hi @jpraysz2 , thanks for reaching us. Seems that CSI is configured with the wrong region name. Can you tell us how you are deploying CSI?

**Comment by jpraysz2** [comment]
Hi, 
I finally managed to make it work using an EIM AK instead of my account AK. I guess the message with the eu-west-2 reference was from the API server.
Regards
